version: '3.8'

services:
  openai-to-gemini:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./credentials:/app/credentials
    environment:
      # This is kept for backward compatibility but our app now primarily uses the credential manager
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
      # Directory where credential files are stored (used by credential manager)
      - CREDENTIALS_DIR=/app/credentials
    restart: unless-stopped